---
- name: Install Docker dependencies
  apt: 
    name: "{{ packages }}"
  vars:
    packages:
      - python 
      - python-simplejson
      - python-dev
      - python-setuptools
      - python-pip
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - bridge-utils
    update_cache: yes

##NO NECESARIA PARA UBUNTU 18.XX +
# - name: Install pip
#   easy_install:
#       name=pip
#       state=latest

- name: Install docker-py
  pip:
      name=docker-py
      state=latest
      
