---
# handlers file for docker
- name: restart docker
  service: "name=docker state={{ docker_restart_handler_state }}"

- name: stop docker
  service: "name=docker state={{ docker_stop_handler_state }}"

- name: reload systemd
#  sudo: yes
  command: systemctl daemon-reload

- meta: flush_handlers
